// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace _7WondersEvaluation.Migrations
{
    [DbContext(typeof(GameContext))]
    [Migration("20240216194434_requried")]
    partial class requried
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("Evaluation", b =>
                {
                    b.Property<int>("EvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Blue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Coins")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExpansionStages")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Green")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Red")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Violet")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Yellow")
                        .HasColumnType("INTEGER");

                    b.HasKey("EvaluationId");

                    b.HasIndex("GameId", "PlayerId")
                        .IsUnique();

                    b.ToTable("Evaluation");
                });

            modelBuilder.Entity("Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GameDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("PlayerOutlay", b =>
                {
                    b.Property<int>("PlayerOutlayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountBlue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountBrown")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountExpa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountGild")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountGreen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountGrey")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountNegWarMarker")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountRed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountWarMarker")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountYellow")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gilds")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerOutlayId");

                    b.HasIndex("GameId", "PlayerId")
                        .IsUnique();

                    b.ToTable("PlayerOutlay");
                });

            modelBuilder.Entity("PlayersInGame", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionInGame")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayersInGame");
                });

            modelBuilder.Entity("Evaluation", b =>
                {
                    b.HasOne("PlayersInGame", "PlayersInGame")
                        .WithOne("Evaluation")
                        .HasForeignKey("Evaluation", "GameId", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("PlayersInGame");
                });

            modelBuilder.Entity("PlayerOutlay", b =>
                {
                    b.HasOne("PlayersInGame", "PlayersInGame")
                        .WithOne("PlayerOutlay")
                        .HasForeignKey("PlayerOutlay", "GameId", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("PlayersInGame");
                });

            modelBuilder.Entity("PlayersInGame", b =>
                {
                    b.HasOne("Game", "Game")
                        .WithMany("PlayersInGame")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Player", "Player")
                        .WithMany("PlayersInGame")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Game", b =>
                {
                    b.Navigation("PlayersInGame");
                });

            modelBuilder.Entity("Player", b =>
                {
                    b.Navigation("PlayersInGame");
                });

            modelBuilder.Entity("PlayersInGame", b =>
                {
                    b.Navigation("Evaluation");

                    b.Navigation("PlayerOutlay");
                });
#pragma warning restore 612, 618
        }
    }
}
